// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package org.stackroute.grpc;

public final class Recommendation {
  private Recommendation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface recommendmessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recommendmessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>int32 job_id = 2;</code>
     * @return The jobId.
     */
    int getJobId();

    /**
     * <code>string job_recommendation_title = 3;</code>
     * @return The jobRecommendationTitle.
     */
    java.lang.String getJobRecommendationTitle();
    /**
     * <code>string job_recommendation_title = 3;</code>
     * @return The bytes for jobRecommendationTitle.
     */
    com.google.protobuf.ByteString
        getJobRecommendationTitleBytes();

    /**
     * <code>string job_recommendation_details = 4;</code>
     * @return The jobRecommendationDetails.
     */
    java.lang.String getJobRecommendationDetails();
    /**
     * <code>string job_recommendation_details = 4;</code>
     * @return The bytes for jobRecommendationDetails.
     */
    com.google.protobuf.ByteString
        getJobRecommendationDetailsBytes();
  }
  /**
   * Protobuf type {@code recommendmessage}
   */
  public  static final class recommendmessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recommendmessage)
      recommendmessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use recommendmessage.newBuilder() to construct.
    private recommendmessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private recommendmessage() {
      jobRecommendationTitle_ = "";
      jobRecommendationDetails_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new recommendmessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private recommendmessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {

              jobId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              jobRecommendationTitle_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              jobRecommendationDetails_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.stackroute.grpc.Recommendation.internal_static_recommendmessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.stackroute.grpc.Recommendation.internal_static_recommendmessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.stackroute.grpc.Recommendation.recommendmessage.class, org.stackroute.grpc.Recommendation.recommendmessage.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }

    public static final int JOB_ID_FIELD_NUMBER = 2;
    private int jobId_;
    /**
     * <code>int32 job_id = 2;</code>
     * @return The jobId.
     */
    public int getJobId() {
      return jobId_;
    }

    public static final int JOB_RECOMMENDATION_TITLE_FIELD_NUMBER = 3;
    private volatile java.lang.Object jobRecommendationTitle_;
    /**
     * <code>string job_recommendation_title = 3;</code>
     * @return The jobRecommendationTitle.
     */
    public java.lang.String getJobRecommendationTitle() {
      java.lang.Object ref = jobRecommendationTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobRecommendationTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string job_recommendation_title = 3;</code>
     * @return The bytes for jobRecommendationTitle.
     */
    public com.google.protobuf.ByteString
        getJobRecommendationTitleBytes() {
      java.lang.Object ref = jobRecommendationTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobRecommendationTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOB_RECOMMENDATION_DETAILS_FIELD_NUMBER = 4;
    private volatile java.lang.Object jobRecommendationDetails_;
    /**
     * <code>string job_recommendation_details = 4;</code>
     * @return The jobRecommendationDetails.
     */
    public java.lang.String getJobRecommendationDetails() {
      java.lang.Object ref = jobRecommendationDetails_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobRecommendationDetails_ = s;
        return s;
      }
    }
    /**
     * <code>string job_recommendation_details = 4;</code>
     * @return The bytes for jobRecommendationDetails.
     */
    public com.google.protobuf.ByteString
        getJobRecommendationDetailsBytes() {
      java.lang.Object ref = jobRecommendationDetails_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobRecommendationDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (jobId_ != 0) {
        output.writeInt32(2, jobId_);
      }
      if (!getJobRecommendationTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jobRecommendationTitle_);
      }
      if (!getJobRecommendationDetailsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, jobRecommendationDetails_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (jobId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jobId_);
      }
      if (!getJobRecommendationTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jobRecommendationTitle_);
      }
      if (!getJobRecommendationDetailsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, jobRecommendationDetails_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.stackroute.grpc.Recommendation.recommendmessage)) {
        return super.equals(obj);
      }
      org.stackroute.grpc.Recommendation.recommendmessage other = (org.stackroute.grpc.Recommendation.recommendmessage) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getJobId()
          != other.getJobId()) return false;
      if (!getJobRecommendationTitle()
          .equals(other.getJobRecommendationTitle())) return false;
      if (!getJobRecommendationDetails()
          .equals(other.getJobRecommendationDetails())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
      hash = (53 * hash) + getJobId();
      hash = (37 * hash) + JOB_RECOMMENDATION_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getJobRecommendationTitle().hashCode();
      hash = (37 * hash) + JOB_RECOMMENDATION_DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getJobRecommendationDetails().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.recommendmessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.stackroute.grpc.Recommendation.recommendmessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recommendmessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recommendmessage)
        org.stackroute.grpc.Recommendation.recommendmessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.stackroute.grpc.Recommendation.internal_static_recommendmessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.stackroute.grpc.Recommendation.internal_static_recommendmessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.stackroute.grpc.Recommendation.recommendmessage.class, org.stackroute.grpc.Recommendation.recommendmessage.Builder.class);
      }

      // Construct using org.stackroute.grpc.Recommendation.recommendmessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        jobId_ = 0;

        jobRecommendationTitle_ = "";

        jobRecommendationDetails_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.stackroute.grpc.Recommendation.internal_static_recommendmessage_descriptor;
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.recommendmessage getDefaultInstanceForType() {
        return org.stackroute.grpc.Recommendation.recommendmessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.recommendmessage build() {
        org.stackroute.grpc.Recommendation.recommendmessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.recommendmessage buildPartial() {
        org.stackroute.grpc.Recommendation.recommendmessage result = new org.stackroute.grpc.Recommendation.recommendmessage(this);
        result.userId_ = userId_;
        result.jobId_ = jobId_;
        result.jobRecommendationTitle_ = jobRecommendationTitle_;
        result.jobRecommendationDetails_ = jobRecommendationDetails_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.stackroute.grpc.Recommendation.recommendmessage) {
          return mergeFrom((org.stackroute.grpc.Recommendation.recommendmessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.stackroute.grpc.Recommendation.recommendmessage other) {
        if (other == org.stackroute.grpc.Recommendation.recommendmessage.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getJobId() != 0) {
          setJobId(other.getJobId());
        }
        if (!other.getJobRecommendationTitle().isEmpty()) {
          jobRecommendationTitle_ = other.jobRecommendationTitle_;
          onChanged();
        }
        if (!other.getJobRecommendationDetails().isEmpty()) {
          jobRecommendationDetails_ = other.jobRecommendationDetails_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.stackroute.grpc.Recommendation.recommendmessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.stackroute.grpc.Recommendation.recommendmessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       * @return The userId.
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int jobId_ ;
      /**
       * <code>int32 job_id = 2;</code>
       * @return The jobId.
       */
      public int getJobId() {
        return jobId_;
      }
      /**
       * <code>int32 job_id = 2;</code>
       * @param value The jobId to set.
       * @return This builder for chaining.
       */
      public Builder setJobId(int value) {
        
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 job_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobId() {
        
        jobId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object jobRecommendationTitle_ = "";
      /**
       * <code>string job_recommendation_title = 3;</code>
       * @return The jobRecommendationTitle.
       */
      public java.lang.String getJobRecommendationTitle() {
        java.lang.Object ref = jobRecommendationTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobRecommendationTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string job_recommendation_title = 3;</code>
       * @return The bytes for jobRecommendationTitle.
       */
      public com.google.protobuf.ByteString
          getJobRecommendationTitleBytes() {
        java.lang.Object ref = jobRecommendationTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobRecommendationTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string job_recommendation_title = 3;</code>
       * @param value The jobRecommendationTitle to set.
       * @return This builder for chaining.
       */
      public Builder setJobRecommendationTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobRecommendationTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string job_recommendation_title = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobRecommendationTitle() {
        
        jobRecommendationTitle_ = getDefaultInstance().getJobRecommendationTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string job_recommendation_title = 3;</code>
       * @param value The bytes for jobRecommendationTitle to set.
       * @return This builder for chaining.
       */
      public Builder setJobRecommendationTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobRecommendationTitle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobRecommendationDetails_ = "";
      /**
       * <code>string job_recommendation_details = 4;</code>
       * @return The jobRecommendationDetails.
       */
      public java.lang.String getJobRecommendationDetails() {
        java.lang.Object ref = jobRecommendationDetails_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobRecommendationDetails_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string job_recommendation_details = 4;</code>
       * @return The bytes for jobRecommendationDetails.
       */
      public com.google.protobuf.ByteString
          getJobRecommendationDetailsBytes() {
        java.lang.Object ref = jobRecommendationDetails_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobRecommendationDetails_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string job_recommendation_details = 4;</code>
       * @param value The jobRecommendationDetails to set.
       * @return This builder for chaining.
       */
      public Builder setJobRecommendationDetails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobRecommendationDetails_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string job_recommendation_details = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobRecommendationDetails() {
        
        jobRecommendationDetails_ = getDefaultInstance().getJobRecommendationDetails();
        onChanged();
        return this;
      }
      /**
       * <code>string job_recommendation_details = 4;</code>
       * @param value The bytes for jobRecommendationDetails to set.
       * @return This builder for chaining.
       */
      public Builder setJobRecommendationDetailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobRecommendationDetails_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recommendmessage)
    }

    // @@protoc_insertion_point(class_scope:recommendmessage)
    private static final org.stackroute.grpc.Recommendation.recommendmessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.stackroute.grpc.Recommendation.recommendmessage();
    }

    public static org.stackroute.grpc.Recommendation.recommendmessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<recommendmessage>
        PARSER = new com.google.protobuf.AbstractParser<recommendmessage>() {
      @java.lang.Override
      public recommendmessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new recommendmessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<recommendmessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<recommendmessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.stackroute.grpc.Recommendation.recommendmessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIresponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIresponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responsemessage = 1;</code>
     * @return The responsemessage.
     */
    java.lang.String getResponsemessage();
    /**
     * <code>string responsemessage = 1;</code>
     * @return The bytes for responsemessage.
     */
    com.google.protobuf.ByteString
        getResponsemessageBytes();

    /**
     * <code>int32 responsecode = 2;</code>
     * @return The responsecode.
     */
    int getResponsecode();
  }
  /**
   * Protobuf type {@code APIresponse}
   */
  public  static final class APIresponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIresponse)
      APIresponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIresponse.newBuilder() to construct.
    private APIresponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIresponse() {
      responsemessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new APIresponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIresponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responsemessage_ = s;
              break;
            }
            case 16: {

              responsecode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.stackroute.grpc.Recommendation.internal_static_APIresponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.stackroute.grpc.Recommendation.internal_static_APIresponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.stackroute.grpc.Recommendation.APIresponse.class, org.stackroute.grpc.Recommendation.APIresponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responsemessage_;
    /**
     * <code>string responsemessage = 1;</code>
     * @return The responsemessage.
     */
    public java.lang.String getResponsemessage() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsemessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responsemessage = 1;</code>
     * @return The bytes for responsemessage.
     */
    public com.google.protobuf.ByteString
        getResponsemessageBytes() {
      java.lang.Object ref = responsemessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsemessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responsecode_;
    /**
     * <code>int32 responsecode = 2;</code>
     * @return The responsecode.
     */
    public int getResponsecode() {
      return responsecode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponsemessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responsemessage_);
      }
      if (responsecode_ != 0) {
        output.writeInt32(2, responsecode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponsemessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responsemessage_);
      }
      if (responsecode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responsecode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.stackroute.grpc.Recommendation.APIresponse)) {
        return super.equals(obj);
      }
      org.stackroute.grpc.Recommendation.APIresponse other = (org.stackroute.grpc.Recommendation.APIresponse) obj;

      if (!getResponsemessage()
          .equals(other.getResponsemessage())) return false;
      if (getResponsecode()
          != other.getResponsecode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsemessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponsecode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.stackroute.grpc.Recommendation.APIresponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.stackroute.grpc.Recommendation.APIresponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIresponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIresponse)
        org.stackroute.grpc.Recommendation.APIresponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.stackroute.grpc.Recommendation.internal_static_APIresponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.stackroute.grpc.Recommendation.internal_static_APIresponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.stackroute.grpc.Recommendation.APIresponse.class, org.stackroute.grpc.Recommendation.APIresponse.Builder.class);
      }

      // Construct using org.stackroute.grpc.Recommendation.APIresponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responsemessage_ = "";

        responsecode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.stackroute.grpc.Recommendation.internal_static_APIresponse_descriptor;
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.APIresponse getDefaultInstanceForType() {
        return org.stackroute.grpc.Recommendation.APIresponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.APIresponse build() {
        org.stackroute.grpc.Recommendation.APIresponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.stackroute.grpc.Recommendation.APIresponse buildPartial() {
        org.stackroute.grpc.Recommendation.APIresponse result = new org.stackroute.grpc.Recommendation.APIresponse(this);
        result.responsemessage_ = responsemessage_;
        result.responsecode_ = responsecode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.stackroute.grpc.Recommendation.APIresponse) {
          return mergeFrom((org.stackroute.grpc.Recommendation.APIresponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.stackroute.grpc.Recommendation.APIresponse other) {
        if (other == org.stackroute.grpc.Recommendation.APIresponse.getDefaultInstance()) return this;
        if (!other.getResponsemessage().isEmpty()) {
          responsemessage_ = other.responsemessage_;
          onChanged();
        }
        if (other.getResponsecode() != 0) {
          setResponsecode(other.getResponsecode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.stackroute.grpc.Recommendation.APIresponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.stackroute.grpc.Recommendation.APIresponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responsemessage_ = "";
      /**
       * <code>string responsemessage = 1;</code>
       * @return The responsemessage.
       */
      public java.lang.String getResponsemessage() {
        java.lang.Object ref = responsemessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responsemessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @return The bytes for responsemessage.
       */
      public com.google.protobuf.ByteString
          getResponsemessageBytes() {
        java.lang.Object ref = responsemessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responsemessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @param value The responsemessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponsemessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responsemessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponsemessage() {
        
        responsemessage_ = getDefaultInstance().getResponsemessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responsemessage = 1;</code>
       * @param value The bytes for responsemessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponsemessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responsemessage_ = value;
        onChanged();
        return this;
      }

      private int responsecode_ ;
      /**
       * <code>int32 responsecode = 2;</code>
       * @return The responsecode.
       */
      public int getResponsecode() {
        return responsecode_;
      }
      /**
       * <code>int32 responsecode = 2;</code>
       * @param value The responsecode to set.
       * @return This builder for chaining.
       */
      public Builder setResponsecode(int value) {
        
        responsecode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responsecode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponsecode() {
        
        responsecode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIresponse)
    }

    // @@protoc_insertion_point(class_scope:APIresponse)
    private static final org.stackroute.grpc.Recommendation.APIresponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.stackroute.grpc.Recommendation.APIresponse();
    }

    public static org.stackroute.grpc.Recommendation.APIresponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIresponse>
        PARSER = new com.google.protobuf.AbstractParser<APIresponse>() {
      @java.lang.Override
      public APIresponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIresponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIresponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIresponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.stackroute.grpc.Recommendation.APIresponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommendmessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommendmessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIresponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIresponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024recommendation.proto\"y\n\020recommendmessa" +
      "ge\022\017\n\007user_id\030\001 \001(\005\022\016\n\006job_id\030\002 \001(\005\022 \n\030j" +
      "ob_recommendation_title\030\003 \001(\t\022\"\n\032job_rec" +
      "ommendation_details\030\004 \001(\t\"<\n\013APIresponse" +
      "\022\027\n\017responsemessage\030\001 \001(\t\022\024\n\014responsecod" +
      "e\030\002 \001(\0052>\n\016recommendation\022,\n\trecommend\022\021" +
      ".recommendmessage\032\014.APIresponseB\025\n\023org.s" +
      "tackroute.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_recommendmessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recommendmessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommendmessage_descriptor,
        new java.lang.String[] { "UserId", "JobId", "JobRecommendationTitle", "JobRecommendationDetails", });
    internal_static_APIresponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIresponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIresponse_descriptor,
        new java.lang.String[] { "Responsemessage", "Responsecode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
