// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface allResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  java.util.List<org.stackroute.register.allr> 
      getSearchResultList();
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  org.stackroute.register.allr getSearchResult(int index);
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  int getSearchResultCount();
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  java.util.List<? extends org.stackroute.register.allrOrBuilder> 
      getSearchResultOrBuilderList();
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  org.stackroute.register.allrOrBuilder getSearchResultOrBuilder(
      int index);
}
