// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface allMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string search = 1;</code>
   */
  java.lang.String getSearch();
  /**
   * <code>string search = 1;</code>
   */
  com.google.protobuf.ByteString
      getSearchBytes();
}
