// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

/**
 * Protobuf type {@code allResponse}
 */
public  final class allResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:allResponse)
    allResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use allResponse.newBuilder() to construct.
  private allResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private allResponse() {
    searchResult_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private allResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              searchResult_ = new java.util.ArrayList<org.stackroute.register.allr>();
              mutable_bitField0_ |= 0x00000001;
            }
            searchResult_.add(
                input.readMessage(org.stackroute.register.allr.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        searchResult_ = java.util.Collections.unmodifiableList(searchResult_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.stackroute.register.Userservice.internal_static_allResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.stackroute.register.Userservice.internal_static_allResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.stackroute.register.allResponse.class, org.stackroute.register.allResponse.Builder.class);
  }

  public static final int SEARCHRESULT_FIELD_NUMBER = 1;
  private java.util.List<org.stackroute.register.allr> searchResult_;
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  public java.util.List<org.stackroute.register.allr> getSearchResultList() {
    return searchResult_;
  }
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  public java.util.List<? extends org.stackroute.register.allrOrBuilder> 
      getSearchResultOrBuilderList() {
    return searchResult_;
  }
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  public int getSearchResultCount() {
    return searchResult_.size();
  }
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  public org.stackroute.register.allr getSearchResult(int index) {
    return searchResult_.get(index);
  }
  /**
   * <code>repeated .allr searchResult = 1;</code>
   */
  public org.stackroute.register.allrOrBuilder getSearchResultOrBuilder(
      int index) {
    return searchResult_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < searchResult_.size(); i++) {
      output.writeMessage(1, searchResult_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < searchResult_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, searchResult_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.stackroute.register.allResponse)) {
      return super.equals(obj);
    }
    org.stackroute.register.allResponse other = (org.stackroute.register.allResponse) obj;

    boolean result = true;
    result = result && getSearchResultList()
        .equals(other.getSearchResultList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSearchResultCount() > 0) {
      hash = (37 * hash) + SEARCHRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getSearchResultList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.stackroute.register.allResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stackroute.register.allResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stackroute.register.allResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stackroute.register.allResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stackroute.register.allResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.stackroute.register.allResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.stackroute.register.allResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.stackroute.register.allResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.stackroute.register.allResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.stackroute.register.allResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.stackroute.register.allResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.stackroute.register.allResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.stackroute.register.allResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code allResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:allResponse)
      org.stackroute.register.allResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.stackroute.register.Userservice.internal_static_allResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.stackroute.register.Userservice.internal_static_allResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.stackroute.register.allResponse.class, org.stackroute.register.allResponse.Builder.class);
    }

    // Construct using org.stackroute.register.allResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSearchResultFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (searchResultBuilder_ == null) {
        searchResult_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        searchResultBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.stackroute.register.Userservice.internal_static_allResponse_descriptor;
    }

    @java.lang.Override
    public org.stackroute.register.allResponse getDefaultInstanceForType() {
      return org.stackroute.register.allResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.stackroute.register.allResponse build() {
      org.stackroute.register.allResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.stackroute.register.allResponse buildPartial() {
      org.stackroute.register.allResponse result = new org.stackroute.register.allResponse(this);
      int from_bitField0_ = bitField0_;
      if (searchResultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          searchResult_ = java.util.Collections.unmodifiableList(searchResult_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.searchResult_ = searchResult_;
      } else {
        result.searchResult_ = searchResultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.stackroute.register.allResponse) {
        return mergeFrom((org.stackroute.register.allResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.stackroute.register.allResponse other) {
      if (other == org.stackroute.register.allResponse.getDefaultInstance()) return this;
      if (searchResultBuilder_ == null) {
        if (!other.searchResult_.isEmpty()) {
          if (searchResult_.isEmpty()) {
            searchResult_ = other.searchResult_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSearchResultIsMutable();
            searchResult_.addAll(other.searchResult_);
          }
          onChanged();
        }
      } else {
        if (!other.searchResult_.isEmpty()) {
          if (searchResultBuilder_.isEmpty()) {
            searchResultBuilder_.dispose();
            searchResultBuilder_ = null;
            searchResult_ = other.searchResult_;
            bitField0_ = (bitField0_ & ~0x00000001);
            searchResultBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSearchResultFieldBuilder() : null;
          } else {
            searchResultBuilder_.addAllMessages(other.searchResult_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.stackroute.register.allResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.stackroute.register.allResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.stackroute.register.allr> searchResult_ =
      java.util.Collections.emptyList();
    private void ensureSearchResultIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        searchResult_ = new java.util.ArrayList<org.stackroute.register.allr>(searchResult_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.stackroute.register.allr, org.stackroute.register.allr.Builder, org.stackroute.register.allrOrBuilder> searchResultBuilder_;

    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public java.util.List<org.stackroute.register.allr> getSearchResultList() {
      if (searchResultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(searchResult_);
      } else {
        return searchResultBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public int getSearchResultCount() {
      if (searchResultBuilder_ == null) {
        return searchResult_.size();
      } else {
        return searchResultBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public org.stackroute.register.allr getSearchResult(int index) {
      if (searchResultBuilder_ == null) {
        return searchResult_.get(index);
      } else {
        return searchResultBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder setSearchResult(
        int index, org.stackroute.register.allr value) {
      if (searchResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchResultIsMutable();
        searchResult_.set(index, value);
        onChanged();
      } else {
        searchResultBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder setSearchResult(
        int index, org.stackroute.register.allr.Builder builderForValue) {
      if (searchResultBuilder_ == null) {
        ensureSearchResultIsMutable();
        searchResult_.set(index, builderForValue.build());
        onChanged();
      } else {
        searchResultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder addSearchResult(org.stackroute.register.allr value) {
      if (searchResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchResultIsMutable();
        searchResult_.add(value);
        onChanged();
      } else {
        searchResultBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder addSearchResult(
        int index, org.stackroute.register.allr value) {
      if (searchResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchResultIsMutable();
        searchResult_.add(index, value);
        onChanged();
      } else {
        searchResultBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder addSearchResult(
        org.stackroute.register.allr.Builder builderForValue) {
      if (searchResultBuilder_ == null) {
        ensureSearchResultIsMutable();
        searchResult_.add(builderForValue.build());
        onChanged();
      } else {
        searchResultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder addSearchResult(
        int index, org.stackroute.register.allr.Builder builderForValue) {
      if (searchResultBuilder_ == null) {
        ensureSearchResultIsMutable();
        searchResult_.add(index, builderForValue.build());
        onChanged();
      } else {
        searchResultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder addAllSearchResult(
        java.lang.Iterable<? extends org.stackroute.register.allr> values) {
      if (searchResultBuilder_ == null) {
        ensureSearchResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, searchResult_);
        onChanged();
      } else {
        searchResultBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder clearSearchResult() {
      if (searchResultBuilder_ == null) {
        searchResult_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        searchResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public Builder removeSearchResult(int index) {
      if (searchResultBuilder_ == null) {
        ensureSearchResultIsMutable();
        searchResult_.remove(index);
        onChanged();
      } else {
        searchResultBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public org.stackroute.register.allr.Builder getSearchResultBuilder(
        int index) {
      return getSearchResultFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public org.stackroute.register.allrOrBuilder getSearchResultOrBuilder(
        int index) {
      if (searchResultBuilder_ == null) {
        return searchResult_.get(index);  } else {
        return searchResultBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public java.util.List<? extends org.stackroute.register.allrOrBuilder> 
         getSearchResultOrBuilderList() {
      if (searchResultBuilder_ != null) {
        return searchResultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(searchResult_);
      }
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public org.stackroute.register.allr.Builder addSearchResultBuilder() {
      return getSearchResultFieldBuilder().addBuilder(
          org.stackroute.register.allr.getDefaultInstance());
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public org.stackroute.register.allr.Builder addSearchResultBuilder(
        int index) {
      return getSearchResultFieldBuilder().addBuilder(
          index, org.stackroute.register.allr.getDefaultInstance());
    }
    /**
     * <code>repeated .allr searchResult = 1;</code>
     */
    public java.util.List<org.stackroute.register.allr.Builder> 
         getSearchResultBuilderList() {
      return getSearchResultFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.stackroute.register.allr, org.stackroute.register.allr.Builder, org.stackroute.register.allrOrBuilder> 
        getSearchResultFieldBuilder() {
      if (searchResultBuilder_ == null) {
        searchResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.stackroute.register.allr, org.stackroute.register.allr.Builder, org.stackroute.register.allrOrBuilder>(
                searchResult_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        searchResult_ = null;
      }
      return searchResultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:allResponse)
  }

  // @@protoc_insertion_point(class_scope:allResponse)
  private static final org.stackroute.register.allResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.stackroute.register.allResponse();
  }

  public static org.stackroute.register.allResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<allResponse>
      PARSER = new com.google.protobuf.AbstractParser<allResponse>() {
    @java.lang.Override
    public allResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new allResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<allResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<allResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.stackroute.register.allResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

