// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface requestMessage2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestMessage2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();
}
