// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface requestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string primarySkil = 1;</code>
   */
  java.lang.String getPrimarySkil();
  /**
   * <code>string primarySkil = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrimarySkilBytes();
}
