// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface requestMessage1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestMessage1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string secondarySkill = 1;</code>
   */
  java.lang.String getSecondarySkill();
  /**
   * <code>string secondarySkill = 1;</code>
   */
  com.google.protobuf.ByteString
      getSecondarySkillBytes();
}
