// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface requestMessage3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestMessage3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string designation = 1;</code>
   */
  java.lang.String getDesignation();
  /**
   * <code>string designation = 1;</code>
   */
  com.google.protobuf.ByteString
      getDesignationBytes();
}
