// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface userIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 userId = 1;</code>
   */
  java.util.List<java.lang.Integer> getUserIdList();
  /**
   * <code>repeated int32 userId = 1;</code>
   */
  int getUserIdCount();
  /**
   * <code>repeated int32 userId = 1;</code>
   */
  int getUserId(int index);
}
