// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface APIresponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIresponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   * @return The responseCode.
   */
  int getResponseCode();
}
