// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package org.stackroute.register;

public interface searchMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:searchMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userEmail = 1;</code>
   * @return The userEmail.
   */
  java.lang.String getUserEmail();
  /**
   * <code>string userEmail = 1;</code>
   * @return The bytes for userEmail.
   */
  com.google.protobuf.ByteString
      getUserEmailBytes();
}
