// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAuth.proto

package org.stackroute.userAuthentication;

public interface responseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 otp = 1;</code>
   * @return The otp.
   */
  long getOtp();
}
